// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3FkFNQknJxwPWdl1YOv1Y4LYJ5yu-CSA',
    appId: '1:1070551080352:android:3a7e4a6b875d467804d8c5',
    messagingSenderId: '1070551080352',
    projectId: 'flutter-test-chat-ima',
    storageBucket: 'flutter-test-chat-ima.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT6gSiz9PyD_2zUXNOzhqqNf7sPzntvbM',
    appId: '1:1070551080352:ios:f23d94b62795316e04d8c5',
    messagingSenderId: '1070551080352',
    projectId: 'flutter-test-chat-ima',
    storageBucket: 'flutter-test-chat-ima.appspot.com',
    androidClientId: '1070551080352-5mi3g1nvf242m4ste49eij8e6lkt382t.apps.googleusercontent.com',
    iosClientId: '1070551080352-s8nufrlfjp9caukin80cccuost2uevqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
